tasks:
  - before: >
      [[ ! -z $GNUGPG  ]] &&
      rm -rf ~/.gnupg &&
      cd / &&
      echo $GNUGPG | base64 -d | tar --no-same-owner -xzvf - &&
      git config --global user.signingkey 793731EFDA37E4BC &&
      git config --global commit.gpgsign true &&
      git config --global tag.gpgsign true &&
      export GPG_TTY=$(tty)