name: bake
run-name: Bake and push Docker images, triggered by @${{ github.actor }} on ref ${{ github.ref }}

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        id: docker-hub-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        id: ghcr-login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Obtain Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            forinil/jmeter-alpine
            ghcr.io/${{ github.repository }}
      - name: Set Jmeter version
        id: jmeter-version
        run: |
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            echo "JMETER_VERSION=5.6.2" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "JMETER_VERSION=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi
      - name: Build and push
        id: docker-bake
        uses: docker/bake-action@v3
        env:
          ALPINE_VERSION: latest
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker-metadata.outputs.bake-file }}
          targets: ci
          push: true